export {default as Button} from './components/button'
export {default as Badge} from './components/badge'
export {default as Loading} from './components/loading'
export {default as Space} from './components/space'
export {default as List} from './components/list'
export {default as Card} from './components/card'
export {default as Image} from './components/image'
export {default as Icon} from './components/icon'
export {default as Mask} from './components/mask'
export * from './components/icon/icon'
export {default as NoticeBar} from './components/notice-bar'
export {default as PageIndicator} from './components/page-indicator'
export {default as Steps} from './components/steps'
export {default as CheckList} from './components/check-list'
export {default as Checkbox} from './components/checkbox'
export {default as Input} from './components/input'
export {default as Tag} from './components/tag'
// export {default as WaterMark} from './components/water-mark' // 由于avm中暂时不支持canvas，所以暂时不能使用
// export {default as Radio} from './components/radio' // 暂时不能使用，正在修改中~
export {default as rate} from './components/rate'