export const moduleList = [
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 5,
        "mdName": "tencentAds",
        "userName": "435465329@qq.com",
        "mdPlatform": 2,
        "mdId": 139657,
        "mdDescription": null,
        "mdInfo": null,
        "enInfo": null,
        "mdType": 8,
        "mdVer": "1.2.0",
        "isfree": 0,
        "price": 198,
        "mdState": 0,
        "discount_price": 0,
        "official": 2,
        "key_id": null,
        "num": 1293,
        "taobao_url": null,
        "icon_path": "http://www.apicloud.com/icon_path/be/55/be553b186809d75a9085b28ba58f5a1d.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 1,
        "green_vip": 0,
        "outline": "封装了腾讯广告联盟的SDK，实现了横幅、插屏、开屏、激励视频等主流样式。使用之前须从腾讯广告联盟申请开发者账号并创建应用，获取 APPID 和 对应的广告位id。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "tabBarMenu",
        "userName": "APICloud",
        "mdPlatform": 2,
        "mdId": 653,
        "mdDescription": "底部导航条菜单",
        "mdInfo": "自定义tabbar,底部导航菜单",
        "enInfo": "Bottom navigation menu",
        "mdType": 3,
        "mdVer": "1.0.1",
        "isfree": 1,
        "price": null,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 13004,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1422437905188_tabbarMenu.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "tabBarMenu 生成一个应用底部导航菜单模块，类似qq空间的底部导航菜单，开发者可自定义菜单各种样式",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "UIActionDialog",
        "userName": "3420289830@qq.com",
        "mdPlatform": 2,
        "mdId": 83338,
        "mdDescription": "封装了可以从屏幕底部向上弹出（300毫秒动画）的 action 选择器（datePicker 打开的是3D滚轮效果）。",
        "mdInfo": "封装了可以从屏幕底部向上弹出（300毫秒动画）的 action 选择器（datePicker 打开的是3D滚轮效果）。",
        "enInfo": "UIAction Picker",
        "mdType": 3,
        "mdVer": "1.0.0",
        "isfree": 0,
        "price": 298,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 660,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1562922269290_banner.jpg",
        "identify": null,
        "inside": 0,
        "green_diamond": 1,
        "green_vip": 0,
        "outline": "此模块封装了可以从屏幕底部向上弹出（300毫秒动画）的 action 选择器（datePicker 打开的是3D滚轮效果）。开发者可自定义选择器的样式，也支持自定义是否显示遮罩层及其样式，可监听用户点击事件。 并在监听的事件里自行设置显示/隐藏（show/hide）等模块的相关操作，使模块试用更加灵活，多样。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdApkUrl": "https://www.apicloud.com/zip/3f/40/3f4027a3257c4ecd6ad7adeccf8433fd.zip",
        "mdName": "TencentAptcha",
        "userName": "1124134058@qq.com",
        "mdPlatform": 11,
        "mdId": 88562,
        "mdDescription": "腾讯防水墙验证码",
        "mdInfo": "腾讯防水墙验证码",
        "enInfo": "",
        "mdType": 13,
        "mdVer": "1.0.0",
        "isfree": 1,
        "price": null,
        "mdState": 0,
        "discount_price": 0,
        "official": 2,
        "key_id": null,
        "num": 1299,
        "taobao_url": "",
        "icon_path": "http://www.apicloud.com/icon_path/55/35/553591c8a37994ef6383706c72ee1d45.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "腾讯防水墙滑动验证码、图形验证码，免费调用。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "zjBluetoothPrint",
        "userName": "3420289830@qq.com",
        "mdPlatform": 1,
        "mdId": 87295,
        "mdDescription": "此模块封装了资江热敏打印协议，可通过此模块链接资江打印机完成打印。",
        "mdInfo": "此模块封装了资江热敏打印协议，可通过此模块链接资江打印机完成打印。",
        "enInfo": "Zhi Jiang Bluetooth printer",
        "mdType": 8,
        "mdVer": "1.0.0",
        "isfree": 0,
        "price": 199,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 244,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1565261515733_zjBluetoothPrint.png",
        "identify": "最新",
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "此模块封装了资江热敏打印协议，可通过此模块链接资江打印机完成打印。可实现打印文字，字体设置，打印图片，打印二维码，打印条形码等。并可适配58mm以及80mm打印机。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "vibrateUtil",
        "userName": "3420289830@qq.com",
        "mdPlatform": 2,
        "mdId": 86951,
        "mdDescription": "封装了原生震动，可实现长震动、短震动、以及连续多次震动。",
        "mdInfo": "封装了原生震动，可实现长震动、短震动、以及连续多次震动。",
        "enInfo": "Long vibration, short vibration, and many consecutive vibration",
        "mdType": 2,
        "mdVer": "1.0.0",
        "isfree": 0,
        "price": 38,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 410,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1565141870590_vibrateUtil.png",
        "identify": "最新",
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "封装了原生震动，可实现长震动、短震动、以及连续多次震动。实现ios中3d Touch peek震动、pop震动、以及连续三次震动，以及安卓中时长震动、周期性震动。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "sunmiScan",
        "userName": "3420289830@qq.com",
        "mdPlatform": 1,
        "mdId": 86528,
        "mdDescription": "此模块封装了商米设备红外扫描接口。",
        "mdInfo": "此模块封装了商米设备红外扫描接口。",
        "enInfo": "Infrared scanning",
        "mdType": 2,
        "mdVer": "1.0.0",
        "isfree": 0,
        "price": 298,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 289,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1564743835070_sunmiScan.png",
        "identify": "最新",
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "此模块封装了商米设备红外扫描接口。可通过此模块获取商米设备红外扫描内容。此模块仅在商米设备有效。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "goodsList",
        "userName": "APICloud模块开发者",
        "mdPlatform": 2,
        "mdId": 4405,
        "mdDescription": "可自定义item头像标签及其样式的列表模块",
        "mdInfo": "自定义listview,可自定义item头像标签及其样式的列表模块",
        "enInfo": "List module with customizable item avatar and style",
        "mdType": 3,
        "mdVer": "1.0.0",
        "isfree": 0,
        "price": 98,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 1251,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1478680973702_1460542067167_Goodslist2.jpg",
        "identify": "无",
        "inside": 0,
        "green_diamond": 1,
        "green_vip": 0,
        "outline": "goodsList 封装了一个列表控件，可实现一个可左右拖动 item 的列表视图。开发者可根据需求自定义列表的元素布局，亦可自定义相关字段的样式。支持设置下拉刷新和上拉加载更多事件。支持删除、刷新、插入指定下标（index）的 item 数据。可动态设置 item 侧滑按钮图标、头像。可设置头像标签。本模块是由第三方模块开发者提供，使用本模块需在线云编译安装包。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "personalCenter",
        "userName": "APICloud",
        "mdPlatform": 2,
        "mdId": 29210,
        "mdDescription": "js 圆形头像_js图片模糊,个人中心用户信息样式",
        "mdInfo": "js 圆形头像_js图片模糊,个人中心用户信息样式",
        "enInfo": "User information style at personal center",
        "mdType": 3,
        "mdVer": "1.0.10",
        "isfree": 1,
        "price": null,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 12584,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1422435040700_personalCenter.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "personalCenter 是一个带有图片模糊效果的个人信息展示中心，开发者只需配置相关接口参数即可实现一个原生效果的个人展示中心",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "db",
        "userName": "APICloud",
        "mdPlatform": 2,
        "mdId": 72619,
        "mdDescription": "app数据_app数据存储,数据库操作对象",
        "mdInfo": "app数据_app数据存储,数据库操作对象",
        "enInfo": "Database",
        "mdType": 5,
        "mdVer": "1.0.5",
        "isfree": 1,
        "price": null,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 36529,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1422501673453_db.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "db 模块封装了手机常用数据库 sqlite 的增删改查语句，可实现数据的本地存储，极大的简化了数据持久化问题",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "audioCombine",
        "userName": "3420289830@qq.com",
        "mdPlatform": 0,
        "mdId": 68913,
        "mdDescription": "音频剪切合成",
        "mdInfo": "音频剪切合成",
        "enInfo": "Audio clip synthesis",
        "mdType": 5,
        "mdVer": "1.0.0",
        "isfree": 0,
        "price": 48,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 89,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1546495128757_audioCombine.png",
        "identify": "无",
        "inside": 0,
        "green_diamond": 1,
        "green_vip": 0,
        "outline": "音频合并是指将两个不同的声音文件合成一个声音文件进行输出，剪切是合并的逆向操作，对音视可以进行更精细化的处理~；模块封装了音频合并和音频剪切。\n\n**注意:1.因为iOS的输出格式不支持.mp3,只能设置为.m4a的音频文件\n      2.iOS音频剪切也是支持m4a的音频文件**",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "touchID",
        "userName": "APICloud",
        "mdPlatform": 2,
        "mdId": 66161,
        "mdDescription": "指纹识别，指纹身份验证",
        "mdInfo": "指纹识别，指纹身份验证",
        "enInfo": "iPhone touch ID",
        "mdType": 10,
        "mdVer": "1.0.4",
        "isfree": 1,
        "price": null,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 8726,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1422976214435_touchID.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "touchID封装了系统自带的指纹识别功能，调用此模块可实现用户指纹输入验证登陆app 。使用本模块需要设备硬件支持指纹识别功能，同时要求iOS8.0和Android6.0及以上的操作系统。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "cchelperCaiHongIM",
        "userName": "3420289830@qq.com",
        "mdPlatform": 2,
        "mdId": 47799,
        "mdDescription": "封装了领通科技CChelper彩虹SDK（小智版）（带有IM功能）",
        "mdInfo": "封装了领通科技CChelper彩虹SDK（小智版）（带有IM功能）",
        "enInfo": "Encapsulates the collar tong technology CChelper rainbow SDK (ash) (with IM function)",
        "mdType": 8,
        "mdVer": "1.0.0",
        "isfree": 1,
        "price": null,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 641,
        "taobao_url": "",
        "icon_path": "http://www.apicloud.com/icon_path/fd/da/fddac29b87b48575dc8d569466e9a0a3.png",
        "identify": "无",
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "cchelperCaiHongIM 封装了领通科技CChelper彩虹SDK（小智版）（带有IM功能）。CChelper彩虹SDK专门针对智能硬件设备定制的移动云客服产品。相比普通的移动App，对于智能硬件及其控制App网络连接问题售后反馈的首要问题，CChelper彩虹SDK小智版在专门增加了无线网络勘察功能，大幅提升用户问题的解决效率。只需智能硬件的控制App简单集成，即可在用户需要求助时，由企业客服对该智能硬件及所对应的App进行可视化的远程操作及协助，帮助用户解决智能硬件使用的各类问题。CChelper彩虹SDK可以大大提升客服工程师的服务效率，犹如身临其境，大大降低服务时长，同时为用",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "aliyunLive",
        "userName": "APICloud",
        "mdPlatform": 2,
        "mdId": 39452,
        "mdDescription": "视频直播_直播,aliyunLive 模块封装阿里云直播平台",
        "mdInfo": "视频直播_直播,aliyunLive 模块封装阿里云直播平台",
        "enInfo": "Ali cloud live SDK",
        "mdType": 11,
        "mdVer": "1.0.4",
        "isfree": 1,
        "price": null,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 19832,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1480734934859_阿里云直播.jpg",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "aliyunLive 封装了阿里云视频直播的sdk，该模块包括视频流采集和视频流播放两部分。使用该模块，需要在阿里云官网注册，在控制台创建直播流，并获取播放端相关参数，详情可以参照阿里云直播官网。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 5,
        "mdName": "thumbnailUtil",
        "userName": "3420289830@qq.com",
        "mdPlatform": 2,
        "mdId": 40493,
        "mdDescription": "生成指定图片的缩略图",
        "mdInfo": "生成指定图片的缩略图",
        "enInfo": "",
        "mdType": 5,
        "mdVer": "1.0.0",
        "isfree": 0,
        "price": 66,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 417,
        "taobao_url": "",
        "icon_path": "http://www.apicloud.com/icon_path/d2/ba/d2ba8e94b90a73bece1b6eae9209aea8.jpg",
        "identify": "无",
        "inside": 0,
        "green_diamond": 1,
        "green_vip": 0,
        "outline": "thumbnailUtil封装了大图生成缩略图功能。使用者需要自定义裁剪尺寸,模块会将原始图片等比例放大或缩小至填满自定义尺寸，并以原始图片中心为中心点，将超出自定义尺寸之外的部分裁减掉。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 3,
        "mdName": "aliYunVoice",
        "userName": "3420289830@qq.com",
        "mdPlatform": 2,
        "mdId": 44829,
        "mdDescription": "阿里云提供的语音识别的一句话识别服务和语音合成的功能。",
        "mdInfo": "阿里云提供的语音识别的一句话识别服务和语音合成的功能。",
        "enInfo": "Ali cloud with speech recognition of word recognition and voice synthesis function.",
        "mdType": 10,
        "mdVer": "1.0.0",
        "isfree": 0,
        "price": 99,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 214,
        "taobao_url": "",
        "icon_path": "http://www.apicloud.com/icon_path/4c/9c/4c9c42c4531393ed5997a91f861dc268.jpg",
        "identify": "无",
        "inside": 0,
        "green_diamond": 1,
        "green_vip": 0,
        "outline": "aliYunVoice模块封装了阿里云提供的语音识别的一句话识别服务和语音合成的功能。\n\n使用本模块之前需要先去阿里云控制台[申请appid和appsecret](https://ak-console.aliyun.com/?spm=5176.doc53288.2.5.E3Lcsn#/accesskey)\n\n语音识别服务提供将实时短语音转成文字的功能，可直接用于语音搜索类应用。\n\n语音合成提供将文本转为普通话语音的语音合成功能。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 0,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "bluetooth",
        "userName": "APICloud",
        "mdPlatform": 2,
        "mdId": 346,
        "mdDescription": "通络蓝牙传输数据",
        "mdInfo": "蓝牙开发,通过蓝牙传输文字串，文件，图片等数据",
        "enInfo": "Transmit text string, file, picture by Bluetooth",
        "mdType": 2,
        "mdVer": "1.0.1",
        "isfree": 1,
        "price": null,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 9090,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1422429020373_blueTooth.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "bluetooth 模块封装了系统的蓝牙功能，使用此模块可实现两台设备间无缝传输数据。可传输字符串、图片、视频、文件等各种数据。使用此模块需打开设备蓝牙功能",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "ajpush",
        "userName": "jpush",
        "mdPlatform": 2,
        "mdId": 140528,
        "mdDescription": "封装了极光推送的sdk",
        "mdInfo": "封装了极光推送的sdk",
        "enInfo": "Jpush SDK",
        "mdType": 8,
        "mdVer": "1.2.2",
        "isfree": 1,
        "price": null,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 42387,
        "taobao_url": null,
        "icon_path": "http://module.apicloud.com/icon/1422587354747_ajpush.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "极光推送, ajpush模块封装了极光推送平台的SDK，使用此模块可实现接收推送通知和透传消息功能。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "UIAlivcLivePlayer",
        "userName": "3420289830@qq.com",
        "mdPlatform": 2,
        "mdId": 140484,
        "mdDescription": "带UI界面的阿里云视频播放器",
        "mdInfo": "带UI界面的阿里云视频播放器",
        "enInfo": "Ali cloud video player with UI",
        "mdType": 11,
        "mdVer": "1.0.1",
        "isfree": 0,
        "price": 199,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 98,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1517642174733_1516356240328_商品列表.png",
        "identify": "无",
        "inside": 0,
        "green_diamond": 1,
        "green_vip": 0,
        "outline": "UIAlivcLivePlayer 封装了阿里云的UI播放器，UI播放器拥有高级播放器的基本功能和多套皮肤，主要为快速实现点播播放（详见：产品介绍），配合点播服务获取视频ID或播放地址。使用该模块，需要在阿里云官网注册，在控制台创建直播流，并获取播放端相关参数，详情可以参照阿里云直播官网。[阿里云视频直播](https://www.aliyun.com/product/live?spm=5176.8009263.386557.93.HXmk3r)",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "HeartRate",
        "userName": "3420289830@qq.com",
        "mdPlatform": 2,
        "mdId": 140483,
        "mdDescription": "通过摄像头获取心率",
        "mdInfo": "通过摄像头获取心率",
        "enInfo": "Acquire heart-rate data through camera",
        "mdType": 2,
        "mdVer": "1.0.1",
        "isfree": 0,
        "price": 88,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 26,
        "taobao_url": null,
        "icon_path": "http://module.apicloud.com/icon/1578043241648_HeartRate.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "通过手机的摄像头获取手指里面毛细血管的波动来获取心率值",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "GifImage",
        "userName": "APICloud",
        "mdPlatform": 2,
        "mdId": 140482,
        "mdDescription": "指定位置显示一张 Gif 图",
        "mdInfo": "指定位置显示一张 Gif 图",
        "enInfo": "",
        "mdType": 5,
        "mdVer": "1.0.1",
        "isfree": 1,
        "price": null,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 20,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1637671254352_GifImage.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "指定位置显示一张 Gif 图",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "bookReader",
        "userName": "APICloud",
        "mdPlatform": 2,
        "mdId": 140477,
        "mdDescription": "翻页效果_txt阅读器,具有翻页效果的文本阅读器",
        "mdInfo": "翻页效果_txt阅读器,具有翻页效果的文本阅读器",
        "enInfo": "Text reader with page-flips effect",
        "mdType": 5,
        "mdVer": "1.1.6",
        "isfree": 1,
        "price": null,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 4615,
        "taobao_url": null,
        "icon_path": "http://module.apicloud.com/icon/1422429127648_bookReader.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "本模块是原生实现的一个文本阅读器，开发者只要传进来一个 text 文本文件，配置相应的参数，模块底层即可实现一个翻页效果的图书阅读器",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "hintChatBox",
        "userName": "apicloud",
        "mdPlatform": 2,
        "mdId": 140475,
        "mdDescription": "聊天框_js输入框,带提示文本的聊天输入框",
        "mdInfo": "聊天框_js输入框,带提示文本的聊天输入框",
        "enInfo": "Chat with a tooltip text input box",
        "mdType": 3,
        "mdVer": "1.0.3",
        "isfree": 1,
        "price": null,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 2337,
        "taobao_url": null,
        "icon_path": "http://module.apicloud.com/icon/1464353753685_hintChatBox(1).jpg",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "hintChatBox 是一个聊天输入框模块，集成了表情，从相册选取图片的功能。开发者可自定义表情集，只需简单配置即可实现自定义表情和添加点击事件。开发者可自定义快捷输入面板，用户可选择快捷输入",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "meiQiaPlus",
        "userName": "美洽官方",
        "mdPlatform": 2,
        "mdId": 138254,
        "mdDescription": "实现手机用户与企业保持随时随刻沟通的客服工具。",
        "mdInfo": "实现手机用户与企业保持随时随刻沟通的客服工具。",
        "enInfo": "Customer service tool, constant communication between mobile users and enterprise",
        "mdType": 8,
        "mdVer": "1.0.3",
        "isfree": 1,
        "price": null,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 121,
        "taobao_url": "",
        "icon_path": "http://module.apicloud.com/icon/1619088421262_8.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "美洽是一款实现手机用户与企业保持随时随刻沟通的客服工具。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "appUtils",
        "userName": "3420289830@qq.com",
        "mdPlatform": 1,
        "mdId": 140439,
        "mdDescription": "这是一个应用管理工具模块。",
        "mdInfo": "这是一个应用管理工具模块。",
        "enInfo": "This is an application management tool module",
        "mdType": 5,
        "mdVer": "1.0.5",
        "isfree": 0,
        "price": 138,
        "mdState": 0,
        "discount_price": 0,
        "official": 1,
        "key_id": null,
        "num": 82,
        "taobao_url": null,
        "icon_path": "http://module.apicloud.com/icon/1548927576612_appUtils.png",
        "identify": "无",
        "inside": 0,
        "green_diamond": 1,
        "green_vip": 0,
        "outline": "这是一个页面管理工具模块，可实现应用在后台时打开页面，打开其他应用，设置开机启动，获取设备应用信息，获取状态栏高度等。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "musicPlayer",
        "userName": "176142998@qq.com",
        "mdPlatform": 2,
        "mdId": 140414,
        "mdDescription": null,
        "mdInfo": null,
        "enInfo": null,
        "mdType": 5,
        "mdVer": "1.0.7",
        "isfree": 0,
        "price": 666,
        "mdState": 0,
        "discount_price": 0,
        "official": 2,
        "key_id": null,
        "num": 46,
        "taobao_url": null,
        "icon_path": "http://www.apicloud.com/icon_path/50/7b/507bd9f6ffdcbb65fd485fc522328121.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "musicPlayer封装了原生音乐播器，自带大小界面音乐，同时支持iOS锁屏界面控制，Android通知栏控制音乐播放等功能。",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "emasPushPlus",
        "userName": "770104707@qq.com",
        "mdPlatform": 2,
        "mdId": 140413,
        "mdDescription": null,
        "mdInfo": null,
        "enInfo": null,
        "mdType": 8,
        "mdVer": "1.1.0",
        "isfree": 0,
        "price": 318,
        "mdState": 0,
        "discount_price": 0,
        "official": 2,
        "key_id": null,
        "num": 6,
        "taobao_url": null,
        "icon_path": "http://www.apicloud.com/icon_path/58/71/5871d82b63c359bb2c26741164bb2429.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "封装阿里云EMAS厂商推送SDK，提供移动应用消息推送相关服务\nsdk 版本  android: 3.7.4   ios:1.9.9.5",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "oxVideoRecorder",
        "userName": "jiangpy2000@sina.com",
        "mdPlatform": 2,
        "mdId": 140412,
        "mdDescription": null,
        "mdInfo": null,
        "enInfo": null,
        "mdType": 11,
        "mdVer": "1.0.6",
        "isfree": 0,
        "price": 299,
        "mdState": 0,
        "discount_price": 0,
        "official": 2,
        "key_id": null,
        "num": 31,
        "taobao_url": null,
        "icon_path": "http://www.apicloud.com/icon_path/76/a2/76a21832518be13dbce8512dbfaefe71.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "短视频 录制 滤镜 美颜 特效 音乐合成",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 5,
        "mdName": "playModule",
        "userName": "176142998@qq.com",
        "mdPlatform": 2,
        "mdId": 140411,
        "mdDescription": null,
        "mdInfo": null,
        "enInfo": null,
        "mdType": 5,
        "mdVer": "3.6.4",
        "isfree": 0,
        "price": 666,
        "mdState": 0,
        "discount_price": 0,
        "official": 2,
        "key_id": null,
        "num": 2666,
        "taobao_url": null,
        "icon_path": "http://www.apicloud.com/icon_path/07/ca/07ca96e46dc28303270cf46b23a0e759.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "playModule 封装了视频、音频，音轨切换，边播边缓存，弹幕等功能。使用本模块时可把本模块当做一个 frame 添加在 window 或 frame 上。如果仅需要音频播放，请传isPlayMusic参数为true。(Android从3.2.7版本开始必须使用升级环境编译)",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "tbMobQuhe",
        "userName": "472677037@qq.com",
        "mdPlatform": 1,
        "mdId": 140410,
        "mdDescription": null,
        "mdInfo": null,
        "enInfo": null,
        "mdType": 8,
        "mdVer": "3.2.0",
        "isfree": 1,
        "price": 0,
        "mdState": 0,
        "discount_price": 0,
        "official": 2,
        "key_id": null,
        "num": 7,
        "taobao_url": null,
        "icon_path": "http://www.apicloud.com/icon_path/93/fa/93fafac841685d80eeba217802da6300.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "趣禾广告模块包聚合了众多知名广告联盟，模块囊括了开屏、插屏、激励视频的广告样式； 商务合作以及技术支持请查阅文档概述；",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdName": "tpnsPushPlus",
        "userName": "770104707@qq.com",
        "mdPlatform": 2,
        "mdId": 140409,
        "mdDescription": null,
        "mdInfo": null,
        "enInfo": null,
        "mdType": 8,
        "mdVer": "1.1.0",
        "isfree": 0,
        "price": 318,
        "mdState": 0,
        "discount_price": 0,
        "official": 2,
        "key_id": null,
        "num": 8,
        "taobao_url": null,
        "icon_path": "http://www.apicloud.com/icon_path/a8/1e/a81e46e084bcd836fdc823b08283a55d.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 0,
        "green_vip": null,
        "outline": "封装腾讯tpns(信鸽) 厂商推送SDK，提供移动应用消息推送相关服务\nsdk 版本  android: 1.3.2.0   ios:1.3.4.1",
        "no_ver": 0
    },
    {
        "del": 0,
        "hasUp": 1,
        "hasNew": 0,
        "bind": 0,
        "rating": 0,
        "complexRating": 4,
        "mdApkUrl": "https://www.apicloud.com/zip/48/17/481703918a786e3210553395118449ce.zip",
        "mdName": "TracesrNav",
        "userName": "tower1229@qq.com",
        "mdPlatform": 2,
        "mdId": 140408,
        "mdDescription": null,
        "mdInfo": null,
        "enInfo": null,
        "mdType": 13,
        "mdVer": "1.0.1",
        "isfree": 0,
        "price": 50,
        "mdState": 0,
        "discount_price": 0,
        "official": 2,
        "key_id": null,
        "num": 5,
        "taobao_url": null,
        "icon_path": "http://www.apicloud.com/icon_path/90/4a/904a937504a882a7bd03bf5b59afc302.png",
        "identify": null,
        "inside": 0,
        "green_diamond": 1,
        "green_vip": 0,
        "outline": "觅迹，轻量级室内导航解决方案。应用于商超、景点、园区等区域寻路场景，结合使用场景可以扩展全局消息、商户消息等多样化营销功能。本导航主要应用寻路技术，不是GPS导航，没有定位功能，模块代码为演示项目，购买模块后请联系技术支持",
        "no_ver": 0
    }
]